### ISSUE TITLE
run in windows will throw exception

### ISSUE THREAD

**Issue by jpgtama** [fleipold/jproc#16]
Dear fleipold,

Very thank you for creating this lib. It is very helpful. 

There is one issue which may need to be fixed.

After running a simple example code: 
```
String output = ProcBuilder.run("echo", "Hello World!");
System.out.println("output = " + output);
```
I got exception: 

```
Exception in thread "main" org.buildobjects.process.StartupException: Could not startup process 'echo "Hello World!"'.
	at org.buildobjects.process.Proc.<init>(Proc.java:91)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:205)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:226)
	at com.philips.iscm.workutils.collins.epub.WordListMdFile.main(WordListMdFile.java:23)
Caused by: java.io.IOException: Cannot run program "echo": CreateProcess error=2, 系统找不到指定的文件(which means system can't find the file or directory)。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.buildobjects.process.Proc.<init>(Proc.java:77)
	... 3 more
Caused by: java.io.IOException: CreateProcess error=2, 系统找不到指定的文件(which means system can't find the file or directory)。
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more
```

My env: 
OS: windows 10
IDE: IDEA
JDK: 8

**Comment by fleipold** [comment]
@jpgtama thanks for your bug report and for using this library.

A working directory is not strictly required. The jdk will fall back to the current directory, as the [javadoc](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html) for ProcessBuilder states:

> a working directory. The default value is the current working directory of the current process, usually the directory named by the system property user.dir. 

I believe that the error message relates to the name of the . In this case `echo`. The command needs to be either a full path or the command needs to be on the path. On windows echo is not a proper program, but built into the shell (on Unix systems it is usually both a proper utility program and a shell built-in command).
